version: "3.7"

services:
  www_mysql_5:
    image: mysql:5.7
    container_name: www_mysql_5
    restart: always
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "www_mysql_5"
      MYSQL_USER: "www_mysql_5"
      MYSQL_PASSWORD: "www_mysql_5"
      MYSQL_ALLOW_EMPTY_PASSWORD: no
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - www_mysql_5_data:/var/lib/mysql
networks:
  webnet:
    name: webnet
    driver: bridge
volumes:
  www_mysql_5_data:
